[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.gd", "php82Extensions.curl"]

[phases.install]
cmds = ["npm install -g npm@latest"]

[phases.build]
cmds = [
  "npm ci",
  "npm run build",
  "php artisan optimize",
  "php artisan event:cache",
  "php artisan view:cache",
  "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"