# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.gd", "php82Extensions.curl"]

[phases.install]
cmds = [
  "node --version",
  "npm --version",
  "php --version"
]

[phases.build]
cmds = [
  "npm ci || npm install",
  "npm run build",
  "php artisan optimize",
  "php artisan event:cache",
  "php artisan view:cache",
  "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"